################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/Eigen-3.3/unsupported/test/BVH.cpp \
../src/Eigen-3.3/unsupported/test/EulerAngles.cpp \
../src/Eigen-3.3/unsupported/test/FFT.cpp \
../src/Eigen-3.3/unsupported/test/FFTW.cpp \
../src/Eigen-3.3/unsupported/test/NonLinearOptimization.cpp \
../src/Eigen-3.3/unsupported/test/NumericalDiff.cpp \
../src/Eigen-3.3/unsupported/test/alignedvector3.cpp \
../src/Eigen-3.3/unsupported/test/autodiff.cpp \
../src/Eigen-3.3/unsupported/test/autodiff_scalar.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_eventcount.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_meta.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_non_blocking_thread_pool.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_runqueue.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_argmax.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_assign.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_broadcast_sycl.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_broadcasting.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_casts.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_chipping.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_comparisons.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_concatenation.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_const.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_contraction.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_convolution.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_custom_index.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_custom_op.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_device_sycl.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_dimension.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_empty.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_expr.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_fft.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_fixed_size.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_forced_eval.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_forced_eval_sycl.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_generator.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_ifft.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_image_patch.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_index_list.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_inflation.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_intdiv.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_io.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_layout_swap.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_lvalue.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_map.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_math.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_mixed_indices.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_morphing.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_notification.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_of_complex.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_of_const_values.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_of_strings.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_padding.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_patch.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_random.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_reduction.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_reduction_sycl.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_ref.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_reverse.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_roundings.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_scan.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_shuffling.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_simple.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_striding.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_sugar.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_sycl.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_symmetry.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_thread_pool.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_uint128.cpp \
../src/Eigen-3.3/unsupported/test/cxx11_tensor_volume_patch.cpp \
../src/Eigen-3.3/unsupported/test/dgmres.cpp \
../src/Eigen-3.3/unsupported/test/forward_adolc.cpp \
../src/Eigen-3.3/unsupported/test/gmres.cpp \
../src/Eigen-3.3/unsupported/test/kronecker_product.cpp \
../src/Eigen-3.3/unsupported/test/levenberg_marquardt.cpp \
../src/Eigen-3.3/unsupported/test/matrix_exponential.cpp \
../src/Eigen-3.3/unsupported/test/matrix_function.cpp \
../src/Eigen-3.3/unsupported/test/matrix_power.cpp \
../src/Eigen-3.3/unsupported/test/matrix_square_root.cpp \
../src/Eigen-3.3/unsupported/test/minres.cpp \
../src/Eigen-3.3/unsupported/test/mpreal_support.cpp \
../src/Eigen-3.3/unsupported/test/openglsupport.cpp \
../src/Eigen-3.3/unsupported/test/polynomialsolver.cpp \
../src/Eigen-3.3/unsupported/test/polynomialutils.cpp \
../src/Eigen-3.3/unsupported/test/sparse_extra.cpp \
../src/Eigen-3.3/unsupported/test/special_functions.cpp \
../src/Eigen-3.3/unsupported/test/splines.cpp 

OBJS += \
./src/Eigen-3.3/unsupported/test/BVH.o \
./src/Eigen-3.3/unsupported/test/EulerAngles.o \
./src/Eigen-3.3/unsupported/test/FFT.o \
./src/Eigen-3.3/unsupported/test/FFTW.o \
./src/Eigen-3.3/unsupported/test/NonLinearOptimization.o \
./src/Eigen-3.3/unsupported/test/NumericalDiff.o \
./src/Eigen-3.3/unsupported/test/alignedvector3.o \
./src/Eigen-3.3/unsupported/test/autodiff.o \
./src/Eigen-3.3/unsupported/test/autodiff_scalar.o \
./src/Eigen-3.3/unsupported/test/cxx11_eventcount.o \
./src/Eigen-3.3/unsupported/test/cxx11_meta.o \
./src/Eigen-3.3/unsupported/test/cxx11_non_blocking_thread_pool.o \
./src/Eigen-3.3/unsupported/test/cxx11_runqueue.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_argmax.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_assign.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_broadcast_sycl.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_broadcasting.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_casts.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_chipping.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_comparisons.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_concatenation.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_const.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_contraction.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_convolution.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_custom_index.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_custom_op.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_device_sycl.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_dimension.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_empty.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_expr.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_fft.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_fixed_size.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_forced_eval.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_forced_eval_sycl.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_generator.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_ifft.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_image_patch.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_index_list.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_inflation.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_intdiv.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_io.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_layout_swap.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_lvalue.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_map.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_math.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_mixed_indices.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_morphing.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_notification.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_of_complex.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_of_const_values.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_of_strings.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_padding.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_patch.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_random.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_reduction.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_reduction_sycl.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_ref.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_reverse.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_roundings.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_scan.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_shuffling.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_simple.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_striding.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_sugar.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_sycl.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_symmetry.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_thread_pool.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_uint128.o \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_volume_patch.o \
./src/Eigen-3.3/unsupported/test/dgmres.o \
./src/Eigen-3.3/unsupported/test/forward_adolc.o \
./src/Eigen-3.3/unsupported/test/gmres.o \
./src/Eigen-3.3/unsupported/test/kronecker_product.o \
./src/Eigen-3.3/unsupported/test/levenberg_marquardt.o \
./src/Eigen-3.3/unsupported/test/matrix_exponential.o \
./src/Eigen-3.3/unsupported/test/matrix_function.o \
./src/Eigen-3.3/unsupported/test/matrix_power.o \
./src/Eigen-3.3/unsupported/test/matrix_square_root.o \
./src/Eigen-3.3/unsupported/test/minres.o \
./src/Eigen-3.3/unsupported/test/mpreal_support.o \
./src/Eigen-3.3/unsupported/test/openglsupport.o \
./src/Eigen-3.3/unsupported/test/polynomialsolver.o \
./src/Eigen-3.3/unsupported/test/polynomialutils.o \
./src/Eigen-3.3/unsupported/test/sparse_extra.o \
./src/Eigen-3.3/unsupported/test/special_functions.o \
./src/Eigen-3.3/unsupported/test/splines.o 

CPP_DEPS += \
./src/Eigen-3.3/unsupported/test/BVH.d \
./src/Eigen-3.3/unsupported/test/EulerAngles.d \
./src/Eigen-3.3/unsupported/test/FFT.d \
./src/Eigen-3.3/unsupported/test/FFTW.d \
./src/Eigen-3.3/unsupported/test/NonLinearOptimization.d \
./src/Eigen-3.3/unsupported/test/NumericalDiff.d \
./src/Eigen-3.3/unsupported/test/alignedvector3.d \
./src/Eigen-3.3/unsupported/test/autodiff.d \
./src/Eigen-3.3/unsupported/test/autodiff_scalar.d \
./src/Eigen-3.3/unsupported/test/cxx11_eventcount.d \
./src/Eigen-3.3/unsupported/test/cxx11_meta.d \
./src/Eigen-3.3/unsupported/test/cxx11_non_blocking_thread_pool.d \
./src/Eigen-3.3/unsupported/test/cxx11_runqueue.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_argmax.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_assign.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_broadcast_sycl.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_broadcasting.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_casts.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_chipping.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_comparisons.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_concatenation.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_const.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_contraction.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_convolution.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_custom_index.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_custom_op.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_device_sycl.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_dimension.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_empty.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_expr.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_fft.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_fixed_size.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_forced_eval.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_forced_eval_sycl.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_generator.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_ifft.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_image_patch.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_index_list.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_inflation.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_intdiv.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_io.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_layout_swap.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_lvalue.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_map.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_math.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_mixed_indices.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_morphing.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_notification.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_of_complex.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_of_const_values.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_of_strings.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_padding.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_patch.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_random.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_reduction.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_reduction_sycl.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_ref.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_reverse.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_roundings.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_scan.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_shuffling.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_simple.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_striding.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_sugar.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_sycl.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_symmetry.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_thread_pool.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_uint128.d \
./src/Eigen-3.3/unsupported/test/cxx11_tensor_volume_patch.d \
./src/Eigen-3.3/unsupported/test/dgmres.d \
./src/Eigen-3.3/unsupported/test/forward_adolc.d \
./src/Eigen-3.3/unsupported/test/gmres.d \
./src/Eigen-3.3/unsupported/test/kronecker_product.d \
./src/Eigen-3.3/unsupported/test/levenberg_marquardt.d \
./src/Eigen-3.3/unsupported/test/matrix_exponential.d \
./src/Eigen-3.3/unsupported/test/matrix_function.d \
./src/Eigen-3.3/unsupported/test/matrix_power.d \
./src/Eigen-3.3/unsupported/test/matrix_square_root.d \
./src/Eigen-3.3/unsupported/test/minres.d \
./src/Eigen-3.3/unsupported/test/mpreal_support.d \
./src/Eigen-3.3/unsupported/test/openglsupport.d \
./src/Eigen-3.3/unsupported/test/polynomialsolver.d \
./src/Eigen-3.3/unsupported/test/polynomialutils.d \
./src/Eigen-3.3/unsupported/test/sparse_extra.d \
./src/Eigen-3.3/unsupported/test/special_functions.d \
./src/Eigen-3.3/unsupported/test/splines.d 


# Each subdirectory must supply rules for building sources it contributes
src/Eigen-3.3/unsupported/test/%.o: ../src/Eigen-3.3/unsupported/test/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -std=c++0x -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


